name: CI with Go and MySQL (no Docker Compose)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go mod tidy

      - name: Wait for MySQL
        run: |
          for i in {1..10}; do
            mysqladmin ping -h 127.0.0.1 -uroot -proot && exit 0 || true
            echo "⏳ Waiting for MySQL..."
            sleep 3
          done
          echo "❌ MySQL did not start" && exit 1

      - name: Run tests
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_HOST: mysql
          MYSQL_PORT: 3306
          MYSQL_DB: test
        run: go test -v ./...
